import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const navStyles = css`
  display: flex;
  gap: 5px;
  background-color: gray;
  color: white;
  height: 50px;
  justify-content: center;
  padding: 15px;

  span {
    padding: 10px;
  }

  #cart {
    display: inline;
    position: absolute;
    right: 50px;
    top: 5px;
  }
`;

export default function Header(props) {
  return (
    <div css={navStyles}>
      <Head>
        <title>umbrella-shop.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <header>
        <nav>
          <span>
            <Link href="/">
              <a>Home</a>
            </Link>
          </span>
          <span>
            <Link href="/products">
              <a>Products</a>
            </Link>
          </span>
          <span>
            <Link href="/contact">
              <a>Contact</a>
            </Link>
          </span>
        </nav>
        <div id="cart">
          <span>{JSON.stringify(props.totalProductsCount)}</span>

          <Link href="/cart">
            <a>
              <Image
                title="Go to cart"
                src="/cart.png"
                width="35px"
                height="35px"
              />
            </a>
          </Link>
          {/* <Link href="/admin/products">
            <a>Admin</a>
          </Link> */}
        </div>
      </header>
    </div>
  );
}
