import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Product() {
  const router = useRouter();
  const { productId } = router.query;
  return (
    <div>
      <Head>
        <title>umbrella-shop.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <header>
        <nav>
          <Link href="/">
            <a>Home</a>
          </Link>
          <Link href="/products">
            <a>Products</a>
          </Link>
        </nav>
      </header>

      <footer className={styles.footer}>
        <a href="/" target="_blank" rel="noopener noreferrer">
          www.umbrella-shop.com{' '}
          <span className={styles.logo}>
            <Image
              src="/favicon.png"
              alt="Vercel Logo"
              width={16}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
