import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';
import { products } from '../../util/database';

export default function Products() {
  return (
    <div>
      <Head>
        <title>umbrella-shop.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <header>
        <nav>
          <Link href="/">
            <a>Home</a>
          </Link>
          <Link href="/products">
            <a>Products</a>
          </Link>
        </nav>
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>Umbrella Shop</h1>
        <ul>
          {products.map((product) => (
            <li key={`prod-${product.name}`}>
              <Image
                src={product.url}
                width="100px"
                height="100px"
                css={css``}
              />
              <Link href={`/${product.url}`}>
                <a>view here</a>
              </Link>
            </li>
          ))}
        </ul>
        <div
          css={css`
            z-index: -1;
          `}
        >
          <Image
            src="/cloud.jpg"
            alt="Vercel Logo"
            layout="fill"
            css={css`
              opacity: 0.5;
            `}
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="/" target="_blank" rel="noopener noreferrer">
          www.umbrella-shop.com{' '}
          <span className={styles.logo}>
            <Image
              src="/favicon.png"
              alt="Vercel Logo"
              width={16}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
